people/urls.py
from django.conf.urls.defaults import *
from basic.people import views as people_views


urlpatterns = patterns('',
  url(r'^types/(?P<slug>[-\w]+)/$',
    view=people_views.person_type_detail,
    name='person_type_detail'),

  url (r'^types/$',
    view=people_views.person_type_list,
    name='person_type_list'),

  url(r'^(?P<slug>[-\w]+)/$',
    view=people_views.person_detail,
    name='person_detail'),

  url (r'^$',
    view=people_views.person_list,
    name='person_list'),

  url(r'^quotes/(?P<slug>[-\w]+)/$',
    view=people_views.person_quote_list,
    name='person_quote_list'),
)

people/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.db.models import permalink
from django.contrib.auth.models import User

import datetime
import dateutil


class PersonType(models.Model):
    """Person type model."""
    title = models.CharField(_('title'), max_length=100)
    slug = models.SlugField(_('slug'), unique=True)

    class Meta:
        verbose_name = _('person type')
        verbose_name_plural = _('person types')
        db_table = 'people_types'
        ordering = ('title',)

    class Admin:
        pass

    def __unicode__(self):
        return '%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('person_type_detail', None, {'slug': self.slug})


class Person(models.Model):
    """Person model."""
    GENDER_CHOICES = (
        (1, 'Male'),
        (2, 'Female'),
    )
    first_name        = models.CharField(_('first name'), blank=True, max_length=100)
    middle_name       = models.CharField(_('middle name'), blank=True, max_length=100)
    last_name         = models.CharField(_('last name'), blank=True, max_length=100)
    slug              = models.SlugField(_('slug'), unique=True)
    user              = models.ForeignKey(User, blank=True, null=True, help_text='If the person is an existing user of your site.')
    gender            = models.PositiveSmallIntegerField(_('gender'), choices=GENDER_CHOICES, blank=True, null=True)
    mugshot           = models.FileField(_('mugshot'), upload_to='mugshots', blank=True)
    mugshot_credit    = models.CharField(_('mugshot credit'), blank=True, max_length=200)
    birth_date        = models.DateField(_('birth date'), blank=True, null=True)
    person_types      = models.ManyToManyField(PersonType, blank=True)
    website           = models.URLField(_('website'), blank=True, verify_exists=True)

    class Meta:
        verbose_name = _('person')
        verbose_name_plural = _('people')
        db_table = 'people'
        ordering = ('last_name', 'first_name',)

    class Admin:
        list_filter = ('person_types',)
        search_fields = ('first_name', 'last_name')

    def __unicode__(self):
        return u'%s' % self.full_name

    @property
    def full_name(self):
        return u'%s %s' % (self.first_name, self.last_name)

    @property
    def age(self):
        TODAY = datetime.date.today()
        return u'%s' % dateutil.relativedelta(TODAY, self.birth_date).years

    @permalink
    def get_absolute_url(self):
        return ('person_detail', None, {'slug': self.slug})


class Quote(models.Model):
    """Quote model."""
    person            = models.ForeignKey(Person)
    quote             = models.TextField(_('quote'))
    source            = models.CharField(_('source'), blank=True, max_length=255)

    class Meta:
        verbose_name = 'quote'
        verbose_name_plural = 'quotes'
        db_table = 'people_quotes'

    class Admin:
        list_display = ('person','quote')
        list_filter = ('person',)
        search_fields = ('quote',)

    def __unicode__(self):
        return u'%s' % self.quote

    def get_absolute_url(self):
        return self.person.get_absolute_url()


class Conversation(models.Model):
    """A conversation between two or many people."""
    title = models.CharField(blank=True, max_length=200)

    class Admin:
        pass

    def __unicode__(self):
        return self.title


class ConversationItem(models.Model):
    """An item within a conversation."""
    conversation      = models.ForeignKey(Conversation, related_name='items')
    order             = models.PositiveSmallIntegerField()
    speaker           = models.ForeignKey(Person)
    quote             = models.TextField()

    class Meta:
        ordering = ('conversation', 'order')
        unique_together = (('conversation', 'order'),)

    def __unicode__(self):
        return u'%s: %s' % (self.speaker.first_name, self.quote)

people/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import list_detail
from basic.people.models import *


def person_type_detail(request, slug, **kwargs):
    return list_detail.object_detail(
        request,
        queryset = PersonType.objects.all(),
        slug = slug,
        **kwargs
    )
person_type_detail.__doc__ = list_detail.object_detail.__doc__


def person_type_list(request, paginate_by=20, **kwargs):
    return list_detail.object_list(
        request,
        queryset = PersonType.objects.all(),
        paginate_by = paginate_by,
        **kwargs
    )
person_type_list.__doc__ = list_detail.object_list.__doc__


def person_detail(request, slug, **kwargs):
    return list_detail.object_detail(
        request,
        queryset = Person.objects.all(),
        slug = slug,
        **kwargs
    )
person_detail.__doc__ = list_detail.object_detail.__doc__


def person_list(request, paginate_by=20, **kwargs):
    return list_detail.object_list(
        request,
        queryset = Person.objects.all(),
        paginate_by = paginate_by,
        **kwargs
    )
person_list.__doc__ = list_detail.object_list.__doc__


def person_quote_list(request, slug, template_name='people/person_quote_list.html', paginate_by=20, **kwargs):
    person = get_object_or_404(Person, slug__iexact=slug)

    return list_detail.object_list(
        request,
        queryset = person.quote_set.all(),
        paginate_by = paginate_by,
        template_name = template_name,
        extra_context = {'person': person},
        **kwargs
    )
person_quote_list.__doc__ = list_detail.object_list.__doc__

people/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body id="{% block body_id %}{% endblock %}">
  <div id="body">
    {% block body %}
      <div>
        {% block content_title %}{% endblock %}
      </div>
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
  </div>
</body>
</html>

people/templates/people/base_people.html
{% extends "base.html" %}


{% block body_class %}people{% endblock %}

people/templates/people/person_detail.html
{% extends "people/base_people.html" %}


{% block title %}{{ object.full_name }}{% endblock %}


{% block content_title %}
  <h2>{{ object.full_name }}
  <em>{% for type in object.person_types.all %}<a href="{{ type.get_absolute_url }}">{{ type.title }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</em></h2>
{% endblock %}


{% block content %}
  {% if object.book_set.all %}
  <h3 class="list_title">Books</h3>
  <ul class="link_list">
    {% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.full_title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  
  {% if object.band_set.all %}
  <h3 class="list_title">Bands</h3>
  <ul class="link_list">
    {% for band in object.band_set.all %}
    <li><a href="{{ band.get_absolute_url }}">{{ band.full_title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  
  {% if object.movie_set.all %}
  <h3 class="list_title">Movies</h3>
  <ul class="link_list">
    {% for movie in object.movie_set.all %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  
{% endblock %}

people/templates/people/person_list.html
{% extends "people/base_people.html" %}


{% block title %}People{% endblock %}


{% block content_title %}
  <h2>People</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for person in object_list %}
    <li><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

people/templates/people/person_quote_list.html
{% extends "people/base_people.html" %}


{% block title %}{{ person.full_name }}{% endblock %}


{% block content_title %}
  <h2>{{ person.full_name }}
  <em>{% for type in person.person_types.all %}<a href="{{ type.get_absolute_url }}">{{ type.title }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</em></h2>
{% endblock %}


{% block content %}
  {% load markup %}
  
  {% for quote in object_list %}
  <blockquote class="quote">
    {{ quote.quote|markdown:"safe" }}
    <p class="source">&mdash; {{ quote.source }}<p>
  </blockquote>
  {% endfor %}
{% endblock %}

people/templates/people/persontype_detail.html
{% extends "people/base_people.html" %}


{% block title %}{{ object.title }}{% endblock %}


{% block content_title %}
  <h2>{{ object.title }}</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for person in object.person_set.all %}
    <li><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

people/templates/people/persontype_list.html
{% extends "people/base_people.html" %}


{% block title %}Person Types{% endblock %}


{% block content_title %}
  <h2>Person Types</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for person_type in object_list %}
    <li><a href="{{ person_type.get_absolute_url }}">{{ person_type.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}