books/urls.py
from django.conf.urls.defaults import *
from basic.books.models import *


genre_list = {
  'queryset': Genre.objects.all(),
}
publisher_list = {
  'queryset': Publisher.objects.all(),
}
book_list = {
  'queryset': Book.objects.all(),
}


urlpatterns = patterns('',
  url(
    regex   = '^genres/(?P<slug>[-\w]+)/$',
    view    = 'django.views.generic.list_detail.object_detail',
    kwargs  = genre_list,
    name    = 'book_genre_detail',
  ),
  url (
    regex   = '^genres/$',
    view    = 'django.views.generic.list_detail.object_list',
    kwargs  = genre_list,
    name    = 'book_genre_list',
  ),
  url(
    regex   = '^publishers/(?P<slug>[-\w]+)/$',
    view    = 'django.views.generic.list_detail.object_detail',
    kwargs  = publisher_list,
    name    = 'book_publisher_detail',
  ),
  url (
    regex   = '^publishers/$',
    view    = 'django.views.generic.list_detail.object_list',
    kwargs  = publisher_list,
    name    = 'book_publisher_list',
  ),
  url(
    regex   = '^(?P<slug>[-\w]+)/$',
    view    = 'django.views.generic.list_detail.object_detail',
    kwargs  = book_list,
    name    = 'book_detail',
  ),
  url (
    regex   = '^$',
    view    = 'django.views.generic.list_detail.object_list',
    kwargs  = book_list,
    name    = 'book_list',
  ),
)

books/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings
from django.contrib.auth.models import User
from basic.people.models import Person


class Genre(models.Model):
  """ Genre model """
  title         = models.CharField(max_length=100)
  slug          = models.SlugField(unique=True)
  
  class Meta:
    db_table = 'book_genres'
    ordering = ('title',)

  class Admin:
    pass

  def __unicode__(self):
    return '%s' % self.title
  
  @permalink
  def get_absolute_url(self):
    return ('book_genre_detail', None, { 'slug': self.slug })


class Publisher(models.Model):
  """ Publisher """
  title         = models.CharField(max_length=100)
  prefix        = models.CharField(max_length=20, blank=True)
  slug          = models.SlugField(unique=True)
  website       = models.URLField(blank=True, verify_exists=False)
  
  class Meta:
    db_table = 'book_publishers'
    ordering = ('title',)
  
  class Admin:
    pass

  def __unicode__(self):
    return '%s' % self.full_title

  @property
  def full_title(self):
    return '%s %s' % (self.prefix, self.title)
  
  @permalink
  def get_absolute_url(self):
    return ('book_publisher_detail', None, { 'slug':self.slug })


class Book(models.Model):
  """ Listing of books """
  title         = models.CharField(max_length=255)
  prefix        = models.CharField(max_length=20, blank=True)
  subtitle      = models.CharField(blank=True, max_length=255)
  slug          = models.SlugField(unique=True)
  authors       = models.ManyToManyField(Person, limit_choices_to={'person_types__slug__exact': 'author'}, related_name='books')
  isbn          = models.CharField(max_length=14, blank=True)
  pages         = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
  publisher     = models.ForeignKey(Publisher, blank=True, null=True)
  published     = models.DateField(blank=True, null=True)
  cover         = models.FileField(upload_to='books', blank=True)
  description   = models.TextField(blank=True)
  genre         = models.ManyToManyField(Genre, blank=True)
  created       = models.DateTimeField(auto_now_add=True)
  modified      = models.DateTimeField(auto_now=True)
  
  
  class Meta:
    db_table = 'books'
    ordering = ('title',)
  
  class Admin:
    list_display  = ('title', 'pages')
    
  def __unicode__(self):
    return '%s' % self.full_title
  
  @property
  def full_title(self):
    if self.prefix:
      return '%s %s' % (self.prefix, self.title)
    else:
      return '%s' % self.title
  
  @permalink
  def get_absolute_url(self):
    return ('book_detail', None, { 'slug': self.slug })
  
  @property
  def amazon_url(self):
    if self.isbn:
      try:
        return 'http://www.amazon.com/dp/%s/?%s' % (self.isbn, settings.AMAZON_AFFILIATE_EXTENTION)
      except:
        return 'http://www.amazon.com/dp/%s/' % self.isbn


class Highlight(models.Model):
  """ Highlights from books """
  user          = models.ForeignKey(User)
  book          = models.ForeignKey(Book)
  highlight     = models.TextField()
  page          = models.CharField(blank=True, max_length=20)
  created       = models.DateTimeField(auto_now_add=True)
  modified      = models.DateTimeField(auto_now=True)
  
  class Meta:
    db_table = 'book_highlights'
  
  class Admin:
    list_display  = ('book', 'highlight')
    list_filter   = ('book',)
  
  def __unicode__(self):
    return '%s' % self.highlight
  
  @permalink
  def get_absolute_url(self):
    return ('book_detail', None, { 'slug': self.book.slug })


class Page(models.Model):
  """ Page model """
  user          = models.ForeignKey(User)
  book          = models.ForeignKey(Book)
  current_page  = models.PositiveSmallIntegerField(default=0)
  created       = models.DateTimeField(auto_now_add=True)
  
  class Meta:
    db_table = 'book_read_pages'
    ordering = ('-created',)

  class Admin:
    list_display = ('book', 'current_page')

  def __unicode__(self):
    return '%s' % self.current_page

books/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body id="{% block body_id %}{% endblock %}">
  <div id="body">
    {% block body %}
      <div>
        {% block content_title %}{% endblock %}
      </div>
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
  </div>
</body>
</html>

books/templates/books/_nav.html
<div id="section_nav">
  <ul>
    <li class="music"><a href="{% url music_index %}">Music</a></li>
    <li class="movies"><a href="{% url movie_list %}">Movies</a></li>
    <li class="books"><a href="{% url book_list %}">Books</a>
      <ul>
        <li class="genres"><a href="{% url book_genre_list %}">Genres</a></li>
        <li class="publishers"><a href="{% url book_publisher_list %}">Publishers</a></li>
      </ul>
    </li>
  </ul>
</div>

books/templates/books/base_books.html
{% extends "base.html" %}


{% block body_class %}books{% endblock %}

books/templates/books/book_detail.html
{% extends "books/base_books.html" %}


{% block title %}{{ object.full_title }}{% endblock %}


{% block content_title %}
  <h2>Books</h2>
  {% include "books/_nav.html" %}
{% endblock %}


{% block content %}
  {% load markup %}
  <h3>{{ object.full_title }}
    {% if object.subtitle %}<em>{{ object.subtitle }}</em>{% endif %}</h3>
  
  {% if object.cover %}
  <a class="cover" href="{{ object.amazon_url }}"><img src="{{ object.cover.url }}" alt="Book cover"></a>
  {% else %}
  <div class="no_cover"></div>
  {% endif %}
  
  <ul class="info_list">
    <li>Author{{ object.authors.all|pluralize }}: {% for author in object.authors.all %}<a href="{{ author.get_absolute_url }}">{{ author.full_name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>Publisher: <a href="{{ object.publisher.get_absolute_url }}">{{ object.publisher.full_title }}</a></li>
    <li>Released: {{ object.published|date:"d F Y" }}</li>
    <li>Pages: {{ object.pages }} {% if not object.has_read %}on page {{ object.bookmark }}{% endif %}</li>
    <li>Genre: {% for genre in object.genre.all %}{{ genre.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>ISBN: {{ object.isbn }} (<a href="{{ object.amazon_url }}">Amazon</a>)</li>
  </ul>
  
  {% if object.description %}
  <div class="description">
    <h4>Description</h4>
    {{ object.description|markdown:"safe" }}
  </div>
  {% endif %}
  
  {% if object.highlight_set.all %}
  <div class="highlights">
    <h4>Highlights</h4>
    {% for highlight in object.highlight_set.all %}
    <blockquote>
      {{ highlight.highlight|markdown:"safe" }}
      {% if highlight.page %}<p class="source">&mdash; p. {{ highlight.page }}<p>{% endif %}
    </blockquote>
    {% endfor %}
  </div>
  {% endif %}
{% endblock %}

books/templates/books/book_list.html
{% extends "books/base_books.html" %}


{% block title %}Books{% endblock %}


{% block content_title %}
  <h2>Books</h2>
  {% include "books/_nav.html" %}
{% endblock %}


{% block content %}
  <table class="book_table">
    <tr>
      <th>Title</th>
      <th>Authors</th>
      <th>Progress</th>
    </tr>
  {% for book in object_list %}
    <tr>
      <td class="title"><a href="{{ book.get_absolute_url }}">{{ book.title }}{% if book.prefix %}, {{ book.prefix }}{% endif %}</a></td>
      <td class="authors">{% for author in book.authors.all %}<a href="{{ author.get_absolute_url }}">{{ author.full_name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</td>
      <td class="publisher"><a href="{{ book.publisher.get_absolute_url }}">{{ book.publisher.full_title }}</a></td>
    </tr>
  {% endfor %}
  </table>
{% endblock %}

books/templates/books/genre_detail.html
{% extends "books/base_books.html" %}


{% block title %}{{ object.title }}{% endblock %}
{% block body_class %}{{ block.super }} book_genres{% endblock %}


{% block content_title %}
  <h2>Book Genres</h2>
  {% include "books/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.title }}</h3>
  <ul class="link_list">
    {% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

books/templates/books/genre_list.html
{% extends "books/base_books.html" %}


{% block title %}Book Genres{% endblock %}
{% block body_class %}{{ block.super }} book_genres{% endblock %}


{% block content_title %}
  <h2>Book Genres</h2>
  {% include "books/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for genre in object_list %}
    <li><a href="{{ genre.get_absolute_url }}">{{ genre.title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

books/templates/books/publisher_detail.html
{% extends "books/base_books.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} book_publishers{% endblock %}


{% block content_title %}
  <h2>Book Publishers</h2>
  {% include "books/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.full_title }}</h3>
  <ul class="link_list">
    {% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

books/templates/books/publisher_list.html
{% extends "books/base_books.html" %}


{% block title %}Book Publishers{% endblock %}
{% block body_class %}{{ block.super }} book_publishers{% endblock %}


{% block content_title %}
  <h2>Book Publishers</h2>
  {% include "books/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for label in object_list %}
    <li><a href="{{ label.get_absolute_url }}">{{ label.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}